> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Interesting Numpy Array Functions


### Function #4 will shock you!

Numpy is a Python library for handling arrays and matrices as well as the support for executing mathematical functions on these arrays. The list of Numpy array functions that we will be looking today are listed below:

- np.zeros
- np.shape
- np.packbits
- np.char.capitalize
- np.all

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "keviinx/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/keviinx/numpy-array-operations


'https://jovian.ai/keviinx/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.zeros
function2 = np.shape
function3 = np.packbits
function4 = np.char.capitalize
function5 = np.all

## Function 1 - np.zeros

The function basically returns an array filled with zeros based on the matrix given.

In [6]:
# Example 1
np.zeros(5)

array([0., 0., 0., 0., 0.])

Based on example 1, the matrix given was a 5 so the function creates a 1-d array with the dimension of 5.

In [7]:
# Example 2 - working
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In example 2, we pass the matrix of 2x3 and the function then creates a 2-d array with the dimension of 2x3.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

The reason the previous example broke is because the first argument of the zeros function should be in a form of a single int or a tuple. If you pass the argument in the same way shown, the function will take the second argument as a data-type and int is not a valid argument for data-type.

This function can be used when you want to initialize a numpy array and you know the shape but do not know the data to be filled yet, so you just initialize it with zeros first.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "keviinx/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/keviinx/numpy-array-operations


'https://jovian.ai/keviinx/numpy-array-operations'

## Function 2 - np.shape

This function basically returns the shape of the array passed as the argument.

In [10]:
# Example 1 - working
np.shape([5])

(1,)

The example above shows that when given a 1-d array with only one element, the function returns a tuple with only 1 value.

In [11]:
# Example 2 - working
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 8)])
np.shape(a)

(3, 3)

In the second example, we create a variable `a` that holds a 3x3 array and this is also the result when we call the `shape()` function.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
np.shape()

TypeError: _shape_dispatcher() missing 1 required positional argument: 'a'

So in the previous example, the function broke because there were no argument being given when the `shape()` function is called.

This function can be used to determine the shape of an array whenever the data is loaded or the user is unsure what the shape of the array is.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "keviinx/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/keviinx/numpy-array-operations


'https://jovian.ai/keviinx/numpy-array-operations'

## Function 3 - np.packbits

What this function does is basically packs the element of binary-valued array into bits in a uint8 array. The result returned is padded into full bytes with zero bits inserted at the end.

In [14]:
# Example 1 - working
np.packbits([1])

array([128], dtype=uint8)

Since the value of the element is `1`, `packbits()` then just add `0000000` to the back to become `0b10000000 => 128`

In [15]:
# Example 2 - working
np.packbits([0, 0, 0, 0, 0, 0, 1, 1])

array([3], dtype=uint8)

Since the example above contains 8 bits, the `packbits()` will not add any zero padding and just return the uint8 array.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
np.packbits("chicken")

TypeError: Expected an input array of integer or boolean data type

The function broke in the example 3 because the `packbits()` function only accepts array of integers or booleans.

This function should be used when the binary arrays needs to be packed into a uint8 array for further processing.

In [ ]:
jovian.commit()

## Function 4 - np.char.capitalize

The function returns a copy of the array passed with only the first character of each element capitalized.

In [ ]:
# Example 1 - working
np.char.capitalize(["chicken"])

Based on the first example, the `char.capitalize()` function returns the string array with the first character capitalized.

In [17]:
# Example 2 - working
np.char.capitalize(["look", "at", "all", "those", "chickens"])

array(['Look', 'At', 'All', 'Those', 'Chickens'], dtype='<U8')

This example also works the same as the first example and the function returns the string array with the first character capitalized.

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
np.char.capitalize([3])

TypeError: string operation on non-string array

Based on the broken example, we can see that the  function `char.capitalize()` only works if the operation is done on string array.

This function probably can be used on the header row of the dataset which tends to have string as the content of the array.

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "keviinx/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/keviinx/numpy-array-operations


'https://jovian.ai/keviinx/numpy-array-operations'

## Function 5 - np.all

Check all the elements in the array based on the chosen axis whether it is True.

In [20]:
# Example 1 - working
np.all([[True, False],[True, True]])

False

Based on the first example, on of the element in the array is `False` therefore the function `all()` returns `False`.

In [21]:
# Example 2 - working
np.all([[True, False], [True, 1]], axis=1)

array([False,  True])

Given that the `axis` is `1` in the second example, the function returns an array with the value `False` and `True`.

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
np.all([3], [1])

TypeError: 'list' object cannot be interpreted as an integer

The third example is broken because the argument given was not a NumPy array.

This function can be used to check whether all the value in the NumPy array is `True`.

In [ ]:
jovian.commit()

## Conclusion

The five NumPy Array Functions shown is just the tip of the iceberg. Explore the wonderful and amazing world of NumPy!

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* NumPy Tutorial: Your First Steps Into Data Science in Python: https://realpython.com/numpy-tutorial/

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "keviinx/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/keviinx/numpy-array-operations


'https://jovian.ai/keviinx/numpy-array-operations'